[package]
name = "PO2"
version = "0.1.0"
authors = ["Danilo Weber Nunes <danilownunes@gmail.com>"]

[dependencies]
meval = "0.0.9"
gtk = { git = "https://github.com/gtk-rs/gtk.git" , features = ["v3_16"] }
gdk = { git = "https://github.com/gtk-rs/gdk.git"}
